#!/usr/bin/env python3
"""Generate the TradingView Pine scanner scripts that cover the F&O universe.

Why generated and not hand-written: Pine allows a maximum of 40 `request.*()`
calls per script, and a TradingView alert is attached to a script, not to a
symbol. So covering ~210 F&O underlyings means N scripts of 40 symbols each,
every one of them identical apart from its symbol block. Hand-maintaining that
is how symbol lists go stale; regenerating from a text file is not.

Usage:
    python generate_scanners.py                     # rebuild every batch
    python generate_scanners.py --per-script 20     # smaller scripts, if one times out
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import List

sys.path.insert(0, str(Path(__file__).resolve().parent))

from srk.universe import load_symbols, tradingview_symbol  # noqa: E402

ROOT = Path(__file__).resolve().parent
MAX_SECURITY_CALLS = 40          # Pine's hard ceiling on request.*() per script

HEADER = '''//@version=6
// =============================================================================
//  SRK Swing Scanner - {label}   ({count} symbols, {timeframe}m timeframe)
//
//  One script watches {count} F&O underlyings at once and raises a SINGLE
//  TradingView alert naming whichever of them just gave a signal. Pine caps a
//  script at 40 request.security() calls, which is why the F&O list is split
//  across several scripts.
//
//  Signal (the SRK Trading Swing rule, on CLOSED {timeframe}m candles):
//    BULLISH  EMA stack flips to Red > Green > Blue  AND  ADX(14) > 20
//    BEARISH  EMA stack flips to Blue > Green > Red  AND  ADX(14) > 20
//    SL       low of the candle before the flip (bullish) / its high (bearish)
//
//  Setup: add to a {timeframe}m chart -> Alert -> Condition = this script ->
//         "Any alert() function call" -> tick Show popup + Play sound -> Create.
//  Generated by generate_scanners.py - edit that, not this file.
// =============================================================================
indicator("{title}", overlay = true, max_labels_count = 500)

// ---------------------------- Signal settings -------------------------------
tf      = input.timeframe("{timeframe}", "Scan timeframe", group = "Signal")
fastLen = input.int(5,    "Red EMA (fast)",  minval = 1, group = "Signal")
midLen  = input.int(10,   "Green EMA (mid)", minval = 1, group = "Signal")
slowLen = input.int(20,   "Blue EMA (slow)", minval = 1, group = "Signal")
adxLen  = input.int(14,   "ADX length",      minval = 1, group = "Signal")
adxThr  = input.float(20, "ADX threshold",   group = "Signal")

// ---------------------------- Noise filters ---------------------------------
// Measured on b1 (the 40 busiest F&O names) over a real session:
//   defaults below (loose flip, ADX>20) ....... ~13 alerts/day
//   + ADX 25 or 30 ............................. ~4 alerts/day
//   + "Require a flip from the opposite stack" .. ~2 alerts/day
// The last of those matches how rarely the SRK indicator plots a triangle, but
// it is too quiet to be useful as an ALERT - a whole session can pass with one
// signal, fired at 09:15. Start here and tighten only if the flow is too noisy.
alternateOnly   = input.bool(true, "Only alternate signals (no repeat in same direction)", group = "Noise filters")
requireOpposite = input.bool(false, "Require a flip straight from the opposite stack", group = "Noise filters")
cooldownBars    = input.int(0, "Minimum bars between signals", minval = 0, group = "Noise filters")

// ---------------------------- Display settings ------------------------------
showPanel = input.bool(true, "Show scanner panel", group = "Display")
panelPos  = input.string("Top right", "Panel position", group = "Display",
     options = ["Top right", "Top left", "Bottom right", "Bottom left", "Middle right"])
onlyHits  = input.bool(false, "Panel: only symbols signalling right now", group = "Display")
markChart = input.bool(true,  "Draw signals on this chart's own symbol", group = "Display")

// ---------------------------- The SRK swing rule ----------------------------
// Runs once per symbol, inside that symbol's own context via request.security.
srk() =>
    r = ta.ema(close, fastLen)
    g = ta.ema(close, midLen)
    b = ta.ema(close, slowLen)
    [_diP, _diM, adxv] = ta.dmi(adxLen, adxLen)
    up = r > g and g > b                       // RGB: red on top
    dn = b > g and g > r                       // BGR: blue on top
    state = up ? 1 : dn ? -1 : 0
    flip  = state != 0 and state != state[1]   // first bar the stack aligns
    raw   = flip and adxv > adxThr and (not requireOpposite or state[1] == -state)

    // Kept per symbol, because "have we already signalled this swing?" is a
    // per-symbol question and request.security runs this in each one's context.
    var int lastDir = 0
    var int lastBar = -1000000
    fire = raw and (not alternateOnly or state != lastDir) and (bar_index - lastBar >= cooldownBars)
    if fire
        lastDir := state
        lastBar := bar_index

    sig = fire ? state : 0
    sl  = not fire ? na : state == 1 ? low[1] : high[1]
    [sig, state, close, adxv, sl]

// Strip the exchange prefix so alerts read "RELIANCE", not "NSE:RELIANCE".
shortName(s) => str.replace_all(str.replace_all(s, "NSE:", ""), "BSE:", "")

// ---------------------------- Scanned symbols -------------------------------
'''

FOOTER = '''
// ---------------------------- Collect the batch -----------------------------
names  = array.from({names})
sigs   = array.from({sigs})
states = array.from({states})
prices = array.from({prices})
adxs   = array.from({adxs})
sls    = array.from({sls})

// ---------------------------- Alert -----------------------------------------
// One alert() call carries every symbol that fired on this bar, so a single
// TradingView alert covers all {count} of them.
msg  = ""
hits = 0
for i = 0 to array.size(names) - 1
    sg = array.get(sigs, i)
    if sg != 0
        hits += 1
        msg := msg + (msg == "" ? "" : "\\n") + (sg == 1 ? "BULLISH  " : "BEARISH  ") + array.get(names, i) + "  @ " + str.tostring(array.get(prices, i), "#.##") + "  | SL " + str.tostring(array.get(sls, i), "#.##") + "  | ADX " + str.tostring(array.get(adxs, i), "#.0")

if hits > 0 and barstate.isconfirmed
    alert("SRK Swing " + tf + "m - " + str.tostring(hits) + " signal(s)\\n" + msg, alert.freq_once_per_bar_close)

// ---------------------------- On-chart panel --------------------------------
// The scanner's own window: dim green/red = trend stack, bright = fired on this
// bar. This is what makes a hit visible without leaving the chart.
pos = panelPos == "Top left" ? position.top_left : panelPos == "Bottom right" ? position.bottom_right : panelPos == "Bottom left" ? position.bottom_left : panelPos == "Middle right" ? position.middle_right : position.top_right

var table panel = table.new(pos, 5, {rows}, border_width = 1)

if showPanel and barstate.islast
    table.clear(panel, 0, 0, 4, {last_row})
    hdrBg = color.new(color.gray, 20)
    table.cell(panel, 0, 0, "{tag}",  text_color = color.white, bgcolor = hdrBg, text_size = size.tiny)
    table.cell(panel, 1, 0, "SYMBOL", text_color = color.white, bgcolor = hdrBg, text_size = size.tiny)
    table.cell(panel, 2, 0, "TREND",  text_color = color.white, bgcolor = hdrBg, text_size = size.tiny)
    table.cell(panel, 3, 0, "LTP",    text_color = color.white, bgcolor = hdrBg, text_size = size.tiny)
    table.cell(panel, 4, 0, "ADX",    text_color = color.white, bgcolor = hdrBg, text_size = size.tiny)
    row = 1
    for i = 0 to array.size(names) - 1
        sg = array.get(sigs, i)
        st = array.get(states, i)
        if not (onlyHits and sg == 0)
            fired = sg != 0
            bg = sg == 1 ? color.new(color.green, 0) : sg == -1 ? color.new(color.red, 0) : st == 1 ? color.new(color.green, 80) : st == -1 ? color.new(color.red, 80) : color.new(color.gray, 85)
            txt = fired ? color.white : color.gray
            table.cell(panel, 0, row, fired ? "*" : "", text_color = txt, bgcolor = bg, text_size = size.tiny)
            table.cell(panel, 1, row, array.get(names, i), text_color = txt, bgcolor = bg, text_size = size.tiny)
            table.cell(panel, 2, row, st == 1 ? "UP" : st == -1 ? "DOWN" : "-", text_color = txt, bgcolor = bg, text_size = size.tiny)
            table.cell(panel, 3, row, str.tostring(array.get(prices, i), "#.##"), text_color = txt, bgcolor = bg, text_size = size.tiny)
            table.cell(panel, 4, row, str.tostring(array.get(adxs, i), "#.0"), text_color = txt, bgcolor = bg, text_size = size.tiny)
            row += 1
        if row > {count}
            break

// ---------------------------- This chart's own symbol -----------------------
// Same rule drawn on whatever symbol the chart is showing, so the triangles and
// the EMA ribbon match what the scanner is alerting on.
emaR = ta.ema(close, fastLen)
emaG = ta.ema(close, midLen)
emaB = ta.ema(close, slowLen)
plot(markChart ? emaR : na, "Red EMA",   color = color.red,   linewidth = 2)
plot(markChart ? emaG : na, "Green EMA", color = color.green, linewidth = 2)
plot(markChart ? emaB : na, "Blue EMA",  color = color.blue,  linewidth = 2)

[cSig, cState, _cPx, _cAdx, _cSl] = srk()
plotshape(markChart and cSig == 1,  "Bullish", shape.triangleup,   location.belowbar, color.new(color.green, 0), size = size.small, text = "Bullish", textcolor = color.blue)
plotshape(markChart and cSig == -1, "Bearish", shape.triangledown, location.abovebar, color.new(color.red, 0), size = size.small, text = "Bearish", textcolor = color.blue)
bgcolor(markChart ? (cState == 1 ? color.new(color.green, 92) : cState == -1 ? color.new(color.red, 92) : na) : na)
'''


def _joined(prefix: str, count: int, wrap: str = "{}") -> str:
    """Wrap a long array.from(...) argument list at a readable width."""
    items = [wrap.format("%s%02d" % (prefix, i)) for i in range(1, count + 1)]
    out: List[str] = []
    line = ""
    for item in items:
        piece = item + ", "
        if len(line) + len(piece) > 92:
            out.append(line.rstrip())
            line = "     "
        line += piece
    out.append(line.rstrip().rstrip(","))
    return "\n".join(out).strip()


def render(symbols: List[str], *, title: str, label: str, tag: str,
           timeframe: str) -> str:
    n = len(symbols)
    parts = [HEADER.format(label=label, count=n, timeframe=timeframe, title=title)]

    for i, sym in enumerate(symbols, start=1):
        group = "Symbols 1-20" if i <= 20 else "Symbols 21-%d" % n
        parts.append('sym%02d = input.symbol("%s", "%02d", group = "%s")'
                     % (i, tradingview_symbol(sym), i, group))
    parts.append("")
    for i in range(1, n + 1):
        parts.append("[sg%02d, st%02d, px%02d, ad%02d, sl%02d] = "
                     "request.security(sym%02d, tf, srk(), lookahead = barmerge.lookahead_off)"
                     % (i, i, i, i, i, i))

    parts.append(FOOTER.format(
        names=_joined("sym", n, "shortName({})"),
        sigs=_joined("sg", n), states=_joined("st", n),
        prices=_joined("px", n), adxs=_joined("ad", n), sls=_joined("sl", n),
        count=n, rows=n + 1, last_row=n, tag=tag,
    ))
    return "\n".join(parts)


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--symbols", default=str(ROOT / "fno_symbols.txt"))
    ap.add_argument("--out", default=str(ROOT / "pine"))
    ap.add_argument("--per-script", type=int, default=MAX_SECURITY_CALLS,
                    help="symbols per script (Pine caps this at %d)" % MAX_SECURITY_CALLS)
    ap.add_argument("--timeframe", default="15", help="scan timeframe, in minutes")
    args = ap.parse_args()

    if args.per_script > MAX_SECURITY_CALLS:
        print("Pine allows at most %d request.security() calls per script; "
              "--per-script %d would not compile."
              % (MAX_SECURITY_CALLS, args.per_script))
        return 1

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    for stale in out_dir.glob("srk_swing_scanner_*.pine"):
        stale.unlink()

    # No separate "top" script: fno_symbols.txt is kept in turnover order by
    # rank_universe.py, so batch 1 already IS the most-traded 40.
    symbols = load_symbols(Path(args.symbols))
    batches = [symbols[i:i + args.per_script]
               for i in range(0, len(symbols), args.per_script)]
    for n, chunk in enumerate(batches, start=1):
        path = out_dir / ("srk_swing_scanner_b%d.pine" % n)
        path.write_text(render(chunk,
                               title="SRK Swing Scanner B%d (%sm)" % (n, args.timeframe),
                               label="batch %d of %d" % (n, len(batches)),
                               tag="B%d" % n, timeframe=args.timeframe),
                        encoding="utf-8")
        print("%-34s %3d symbols  %s .. %s" % (path.name, len(chunk), chunk[0], chunk[-1]))

    print("\n%d symbols -> %d batch scripts -> %d TradingView alerts for full coverage."
          % (len(symbols), len(batches), len(batches)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
